### ISSUE TITLE
Upgrade to golang v1.12

### ISSUE THREAD

**Issue by geofffranks** [starkandwayne/safe#185]
Any chance safe can start being built with go v1.12? We're experiencing 5-10s dns timeouts when using safe on VMs that have bosh-dns enabled, which appears to be fixed in https://github.com/golang/go/issues/27537 (found via https://github.com/cloudfoundry/locket/issues/7)

**Comment by geofffranks** [comment]
When compiling safe with 1.12 on a linux VM ourselves, the issue went away (dns worked like one would expect, fast and correct)

**Comment by thomasmitchell** [comment]
Absolutely. I just noticed that we were still using 1.9 in the pipelines on Friday. I'm going through a bunch of pipelines today and updating them for various reasons, and that's on my list. Once I have, I'll release a 1.2.1 that has no changes other than to build with 1.12 (just so that apt and brew pick it up sanely)

**Comment by thomasmitchell** [comment]
1.2.1 has your official, me-sanctioned binary. :)

Thanks for telling me.
