### ISSUE TITLE
Initializing vault securely 

### ISSUE THREAD

**Issue by bonzofenix** [starkandwayne/safe#61]
At Allstate we are working on defining the process of initializing and performing rekey processes periodically on a vault server. 

This is our current plan: given a list of emails and PGP pub keys belonging to each of the team member of the platform team we will perform an initialization/rekey process that would generate the master key and split it, encrypt each part of it with the provided keys  and send them via email. 

usage could be something like:

`safe init keys.yml`

would this be suitable for a PR in this project?

**Comment by jhunt** [comment]
It's definitely interesting.  @geofffranks what do you think?

**Comment by geofffranks** [comment]
Each person would get only one of X master keys, or would each person get *all* master keys?

What becomes of the root password in this scenario? Also encrypted/passed out?

I like the sound of it, just curious on implementation details at this point :)

**Comment by automaticgiant** [comment]
i've been thinking about the same thing.
i think the root token would get dropped.
in the case of provisioning, my plan is to start it up the first time, unsealed, with `-dev` and a known root token.
but for later rekey, when vault is already configured, the root token is moot, right?
whenever the team comes together for an unseal, if root is needed, they can also generate.

for the keys, i intend to make use of the pgp support so that distribution is more flexible.
i would assume this would assist `safe` as well. idk that safe needs to send them via email, but that's something that is less important to be decided.

**Comment by jhunt** [comment]
Are you referring to https://www.vaultproject.io/docs/guides/generate-root.html ?

**Comment by automaticgiant** [comment]
right. so root key is moot. kindof like in the case of goldfish https://github.com/Caiyeon/goldfish
